# Generated by Django 2.1.3 on 2018-12-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправки')),
                ('is_success', models.BooleanField(db_index=True, default=False, verbose_name='Успешно?')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
