# Generated by Django 2.1.3 on 2019-01-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={},
        ),
    ]
